I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scenes/start.rpy", line 25, in script
renpy.display.screen.ScreenNotFound: Screen 'main_menu_screen' is not known.

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "game/scenes/start.rpy", line 25, in script
  File "renpy/ast.py", line 2231, in execute
    self.call("execute")
    ~~~~~~~~~^^^^^^^^^^^
  File "renpy/ast.py", line 2195, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/statements.py", line 379, in call
    return method(parsed, *args, **kwargs)
           ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/common/000statements.rpy", line 695, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
                    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/exports/statementexports.py", line 334, in call_screen
    renpy.exports.show_screen(_screen_name, *args, _transient=True, **kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/screen.py", line 1355, in show_screen
    raise ScreenNotFound(name[0])
renpy.display.screen.ScreenNotFound: Screen 'main_menu_screen' is not known.

Linux-6.16.7-arch1-1-x86_64-with-glibc2.42 x86_64
Ren'Py 8.4.1.25072401
renpy_llm 1.0
Sat Sep 20 10:13:35 2025
